backweb1/urls.py
from  django.urls import path
from blog.settings import MEDIA_URL,MEDIA_ROOT


from backweb1 import views

urlpatterns = [

    # 注册账号：
    path('register/',views.register,name='register'),

    # 登录功能
    path('login/',views.login,name='login'),

    # 退出登录
    path('logout/',views.login,name='logout'),

    # 文章功能
    path('article/',views.article,name='article'),

    # 添加文章
    path('add_article/',views.add_article,name='add_article'),

    # 修改文章
    path('update_article/<int:id>/',views.update_article,name='update_article'),

    # 删除文章
    path('del_article/<int:id>/',views.del_article,name='del_article'),

    # 增加栏目
    path('category/',views.category,name='category'),

    # 修改栏目
    path('update_category/<int:id>/',views.update_category,name='update_category'),

    # 删除栏目
    path('del_category/<int:id>/',views.del_category,name='del_category'),
]


from django.contrib.staticfiles.urls import static
urlpatterns += static(MEDIA_URL,document_root=MEDIA_ROOT)

blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    # 前端的路由信息
    path('webevent/',include(('webevent.urls','webevent'),namespace='webevent')),

    # 后端的路由信息
    path('backweb1/',include(('backweb1.urls','backweb1'),namespace='backweb1')),


]

templates/backweb/add-article.html
{% extends 'backweb/base_mian.html' %}



{% block content %}

{{ block.super }}
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-lg-10 col-md-offset-2 main" id="main">
      <div class="row">
        <form action="" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="col-md-9">
            <h1 class="page-header">撰写新文章</h1>
            <div class="form-group">
              <label for="article-title" class="sr-only">标题</label>
              <input type="text" id="article-title" name="title" class="form-control" placeholder="在此处输入标题" required autofocus autocomplete="off">
            </div>
            <div class="form-group">

            </div>
            <div class="add-article-box">

              <h2 class="add-article-box-title"><span>内容</span></h2>
              <div class="add-article-box-content">
              	<input type="text" class="form-control" placeholder="请输入内容" name="content" autocomplete="off">
                <span class="prompt-text">多个标签请用英文逗号,隔开。</span>
              </div>
            </div>
            <div class="">
                <p>图片：<input type="file" name="icon"></p>
            </div>
          </div>
          <div class="col-md-3">
            <h1 class="page-header">操作</h1>
            <div class="add-article-box">
              <h2 class="add-article-box-title"><span>栏目</span></h2>
              <div class="add-article-box-content">
                <ul class="category-list">
                  {% for colu in colus %}

                  <li>

                    <label>
                      <input name="col" type="radio" value="" >
                      {{ colu.c_name }}
                    </label>

                  </li>

                  {% endfor %}
                </ul>
              </div>
            </div>
            <div class="add-article-box">
              <h2 class="add-article-box-title"><span>标签</span></h2>
              <div class="add-article-box-content">
                <input type="text" class="form-control" placeholder="输入新标签" name="tags" autocomplete="off">
                <span class="prompt-text">多个标签请用英文逗号,隔开</span> </div>
            </div>
            <div class="add-article-box">
              <h2 class="add-article-box-title"><span>标题图片</span></h2>
              <div class="add-article-box-content">
                <input type="text" class="form-control" placeholder="点击按钮选择图片" id="pictureUpload" name="titlepic" autocomplete="off">
              </div>
              <div class="add-article-box-footer">
                <button class="btn btn-default" type="button" ID="upImage">选择</button>
              </div>
            </div>
            <div class="add-article-box">
              <h2 class="add-article-box-title"><span>发布</span></h2>
              <div class="add-article-box-content">
              	<p><label>状态：</label><span class="article-status-display">未发布</span></p>
                <p><label>公开度：</label><input type="radio" name="visibility" value="0" checked/>公开 <input type="radio" name="visibility" value="1" />加密</p>
                <p><label>发布于：</label><span class="article-time-display"><input style="border: none;" type="datetime" name="time" value="2016-01-09 17:29:37" /></span></p>
              </div>
              <div class="add-article-box-footer">
                <button class="btn btn-primary" type="submit" name="submit">发布</button>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>
<!--个人信息模态框-->
<div class="modal fade" id="seeUserInfo" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <form action="" method="post">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" >个人信息</h4>
        </div>
        <div class="modal-body">
          <table class="table" style="margin-bottom:0px;">
            <thead>
              <tr> </tr>
            </thead>
            <tbody>
              <tr>
                <td wdith="20%">姓名:</td>
                <td width="80%"><input type="text" value="王雨" class="form-control" name="truename" maxlength="10" autocomplete="off" /></td>
              </tr>
              <tr>
                <td wdith="20%">用户名:</td>
                <td width="80%"><input type="text" value="admin" class="form-control" name="username" maxlength="10" autocomplete="off" /></td>
              </tr>
              <tr>
                <td wdith="20%">电话:</td>
                <td width="80%"><input type="text" value="18538078281" class="form-control" name="usertel" maxlength="13" autocomplete="off" /></td>
              </tr>
              <tr>
                <td wdith="20%">旧密码:</td>
                <td width="80%"><input type="password" class="form-control" name="old_password" maxlength="18" autocomplete="off" /></td>
              </tr>
              <tr>
                <td wdith="20%">新密码:</td>
                <td width="80%"><input type="password" class="form-control" name="password" maxlength="18" autocomplete="off" /></td>
              </tr>
              <tr>
                <td wdith="20%">确认密码:</td>
                <td width="80%"><input type="password" class="form-control" name="new_password" maxlength="18" autocomplete="off" /></td>
              </tr>
            </tbody>
            <tfoot>
              <tr></tr>
            </tfoot>
          </table>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
          <button type="submit" class="btn btn-primary">提交</button>
        </div>
      </div>
    </form>
  </div>
</div>
<!--个人登录记录模态框-->
<div class="modal fade" id="seeUserLoginlog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" >登录记录</h4>
      </div>
      <div class="modal-body">
        <table class="table" style="margin-bottom:0px;">
          <thead>
            <tr>
              <th>登录IP</th>
              <th>登录时间</th>
              <th>状态</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>::1:55570</td>
              <td>2016-01-08 15:50:28</td>
              <td>成功</td>
            </tr>
            <tr>
              <td>::1:64377</td>
              <td>2016-01-08 10:27:44</td>
              <td>成功</td>
            </tr>
            <tr>
              <td>::1:64027</td>
              <td>2016-01-08 10:19:25</td>
              <td>成功</td>
            </tr>
            <tr>
              <td>::1:57081</td>
              <td>2016-01-06 10:35:12</td>
              <td>成功</td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">朕已阅</button>
      </div>
    </div>
  </div>
</div>
<!--微信二维码模态框-->
<div class="modal fade user-select" id="WeChat" tabindex="-1" role="dialog" aria-labelledby="WeChatModalLabel">
  <div class="modal-dialog" role="document" style="margin-top:120px;max-width:280px;">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="WeChatModalLabel" style="cursor:default;">微信扫一扫</h4>
      </div>
      <div class="modal-body" style="text-align:center"> <img src="images/weixin.jpg" alt="" style="cursor:pointer"/> </div>
    </div>
  </div>
</div>
<!--提示模态框-->
<div class="modal fade user-select" id="areDeveloping" tabindex="-1" role="dialog" aria-labelledby="areDevelopingModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="areDevelopingModalLabel" style="cursor:default;">该功能正在日以继夜的开发中…</h4>
      </div>
      <div class="modal-body"> <img src="images/baoman/baoman_01.gif" alt="深思熟虑" />
        <p style="padding:15px 15px 15px 100px; position:absolute; top:15px; cursor:default;">很抱歉，程序猿正在日以继夜的开发此功能，本程序将会在以后的版本中持续完善！</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">朕已阅</button>
      </div>
    </div>
  </div>
</div>
<!--右键菜单列表-->
<div id="rightClickMenu">
  <ul class="list-group rightClickMenuList">
    <li class="list-group-item disabled">欢迎访问异清轩博客</li>
    <li class="list-group-item"><span>IP：</span>172.16.10.129</li>
    <li class="list-group-item"><span>地址：</span>河南省郑州市</li>
    <li class="list-group-item"><span>系统：</span>Windows10 </li>
    <li class="list-group-item"><span>浏览器：</span>Chrome47</li>
  </ul>
</div>
<!--<script src="js/bootstrap.min.js"></script>-->
<!--<script src="js/admin-scripts.js"></script>-->
<!--<script src="lib/ueditor/ueditor.config.js"></script>-->
<!--<script src="lib/ueditor/ueditor.all.min.js"> </script>-->
<!--<script src="lib/ueditor/lang/zh-cn/zh-cn.js"></script>-->
<!--<script id="uploadEditor" type="text/plain" style="display:none;"></script>-->
<!--<script type="text/javascript">-->

<!--window.onresize=function(){-->
    <!--window.location.reload();-->
<!--}-->
<!--var _uploadEditor;-->
<!--$(function () {-->
    <!--//重新实例化一个编辑器，防止在上面的editor编辑器中显示上传的图片或者文件-->
    <!--_uploadEditor = UE.getEditor('uploadEditor');-->
    <!--_uploadEditor.ready(function () {-->
        <!--//设置编辑器不可用-->
        <!--//_uploadEditor.setDisabled();-->
        <!--//隐藏编辑器，因为不会用到这个编辑器实例，所以要隐藏-->
        <!--_uploadEditor.hide();-->
        <!--//侦听图片上传-->
        <!--_uploadEditor.addListener('beforeInsertImage', function (t, arg) {-->
            <!--//将地址赋值给相应的input,只去第一张图片的路径-->
            <!--$("#pictureUpload").attr("value", arg[0].src);-->
            <!--//图片预览-->
            <!--//$("#imgPreview").attr("src", arg[0].src);-->
        <!--})-->
        <!--//侦听文件上传，取上传文件列表中第一个上传的文件的路径-->
        <!--_uploadEditor.addListener('afterUpfile', function (t, arg) {-->
            <!--$("#fileUpload").attr("value", _uploadEditor.options.filePath + arg[0].url);-->
        <!--})-->
    <!--});-->
<!--});-->
<!--//弹出图片上传的对话框-->
<!--$('#upImage').click(function () {-->
    <!--var myImage = _uploadEditor.getDialog("insertimage");-->
    <!--myImage.open();-->
<!--});-->
<!--//弹出文件上传的对话框-->
<!--function upFiles() {-->
    <!--var myFiles = _uploadEditor.getDialog("attachment");-->
    <!--myFiles.open();-->
<!--}-->
<!--</script>-->
{% endblock %}

templates/backweb/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    {% block css %}
    {% endblock %}

    {% block js %}
    {% endblock %}


</head>
<body class="user-select">
    {% block content %}
    {% endblock %}

</body>
</html>

templates/backweb/base_mian.html
{% extends 'backweb/base.html' %}

{% block title %}
    文章 - 异清轩博客管理系统
{% endblock %}

{% block css %}
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="/web/backweb/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/web/backweb/css/style.css">
    <link rel="stylesheet" type="text/css" href="/web/backweb/css/font-awesome.min.css">
    <link rel="apple-touch-icon-precomposed" href="/web/backweb/images/icon/icon.png">
    <link rel="shortcut icon" href="/web/backweb/images/icon/favicon.ico">
{% endblock %}


{% block js %}
    <script src="/web/backweb/js/jquery-2.1.4.min.js"></script>
    <!--[if gte IE 9]>
    <script src="/web/backweb/js/jquery-1.11.1.min.js" type="text/javascript"></script>
    <script src="/web/backweb/js/html5shiv.min.js" type="text/javascript"></script>
    <script src="/web/backweb/js/respond.min.js" type="text/javascript"></script>
    <script src="/web/backweb/js/selectivizr-min.js" type="text/javascript"></script>
    <![endif]-->
    <!--[if lt IE 9]>
    <script>window.location.href='upgrade-browser.html';</script>
    <![endif]-->
{% endblock %}



{% block content %}
<section class="container-fluid">
  <header>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false"> <span class="sr-only">切换导航</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
          <a class="navbar-brand" href="">YlsatCM</a> </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="">消息 <span class="badge">1</span></a></li>
            <li class="dropdown"> <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ user.username }} <span class="caret"></span></a>
              <ul class="dropdown-menu dropdown-menu-left">
                <li><a title="查看或修改个人信息" data-toggle="modal" data-target="#seeUserInfo">个人信息</a></li>
                <li><a title="查看您的登录记录" data-toggle="modal" data-target="#seeUserLoginlog">登录记录</a></li>
              </ul>
            </li>
            <li><a href="{% url 'backweb1:login' %}" onClick="if(!confirm('是否确认退出？'))return false;">退出登录</a></li>
            <li><a data-toggle="modal" data-target="#WeChat">帮助</a></li>
          </ul>
          <form action="" method="post" class="navbar-form navbar-right" role="search">
            <div class="input-group">
              <input type="text" class="form-control" autocomplete="off" placeholder="键入关键字搜索" maxlength="15">
              <span class="input-group-btn">
              <button class="btn btn-default" type="submit">搜索</button>
              </span> </div>
          </form>
        </div>
      </div>
    </nav>
  </header>
 <div class="row">
    <aside class="col-sm-3 col-md-2 col-lg-2 sidebar">
      <ul class="nav nav-sidebar">
        <li><a href="index.html"></a></li>
      </ul>
      <ul class="nav nav-sidebar">
        <li class="active"><a href="">文章</a></li>
        <li><a href="notice.html"></a></li>
        <li><a href="comment.html"></a></li>
        <li><a data-toggle="tooltip" data-placement="top" title="网站暂无留言功能"></a></li>
      </ul>
      <ul class="nav nav-sidebar">
        <li><a href="{% url 'backweb1:category' %}">栏目</a></li>
        <li><a class="dropdown-toggle" id="otherMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></a>
          <ul class="dropdown-menu" aria-labelledby="otherMenu">
            <li><a href="flink.html"></a></li>
            <li><a href="loginlog.html"></a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav nav-sidebar">
        <li><a class="dropdown-toggle" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></a>
          <ul class="dropdown-menu" aria-labelledby="userMenu">
            <li><a href="#">管理用户组</a></li>
            <li><a href="manage-user.html">管理用户</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="loginlog.html">管理登录日志</a></li>
          </ul>
        </li>
        <li><a class="dropdown-toggle" id="settingMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></a>
          <ul class="dropdown-menu" aria-labelledby="settingMenu">
            <li><a href="setting.html">基本设置</a></li>
            <li><a href="readset.html">用户设置</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">安全配置</a></li>
            <li role="separator" class="divider"></li>
            <li class="disabled"><a>扩展菜单</a></li>
          </ul>
        </li>
      </ul>
    </aside>

{% endblock %}

templates/backweb/login.html
<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="renderer" content="webkit">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>黄峰博客管理系统</title>
<link rel="stylesheet" type="text/css" href="/web/backweb/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="/web/backweb/css/style.css">
<link rel="stylesheet" type="text/css" href="/web/backweb/css/login.css">
<link rel="apple-touch-icon-precomposed" href="/web/backweb/images/icon/icon.png">
<!--<link rel="shortcut icon" href="/web/backweb/images/icon/favicon.ico">-->
<script src="/web/backweb/js/jquery-2.1.4.min.js"></script>
<!--[if gte IE 9]>
  <script src="/web/backweb/js/jquery-1.11.1.min.js" type="text/javascript"></script>
  <script src="/web/backweb/js/html5shiv.min.js" type="text/javascript"></script>
  <script src="/web/backweb/js/respond.min.js" type="text/javascript"></script>
  <script src="/web/backweb/js/selectivizr-min.js" type="text/javascript"></script>
<![endif]-->
<!--[if lt IE 9]>
  <script>window.location.href='upgrade-browser.html';</script>
<![endif]-->
</head>

<body class="user-select">
<div class="container">
  <div class="siteIcon"><img src="/web/backweb/images/icon/icon.png" alt="" data-toggle="tooltip" data-placement="top" title="欢迎使用异清轩博客管理系统" draggable="false" /></div>
  <form action="" method="post" autocomplete="off" class="form-signin">
    {% csrf_token %}
    <h2 class="form-signin-heading">管理员登录</h2>
    <label for="userName" class="sr-only">用户名</label>
    <input type="text" id="userName" name="username" class="form-control" placeholder="请输入用户名" required autofocus autocomplete="off" maxlength="10">
    <span>{{ errors.username }}</span>
    <label for="userPwd" class="sr-only">密码</label>
    <input type="password" id="userPwd" name="userpwd" class="form-control" placeholder="请输入密码" required autocomplete="off" maxlength="18">
    <span>{{ errors.userpwd }}</span>
    <a href=""><button class="btn btn-lg btn-primary btn-block" type="submit" id="signinSubmit">登录</button></a>
  </form>
  <div class="footer">
    <p><a href="" data-toggle="tooltip" data-placement="left" title="不知道自己在哪?">回到后台 →</a></p>
  </div>
</div>
<script src="/web/backweb/js/bootstrap.min.js"></script>
<script>
$('[data-toggle="tooltip"]').tooltip();
window.oncontextmenu = function(){
	//return false;
};
$('.siteIcon img').click(function(){
	window.location.reload();
});
$('#signinSubmit').click(function(){
	if($('#userName').val() === ''){
		$(this).text('用户名不能为空');
	}else if($('#userPwd').val() === ''){
		$(this).text('密码不能为空');
	}else{
		$(this).text('请稍后...');
	}
});
</script>
</body>
</html>

templates/backweb/register.html
<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="renderer" content="webkit">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>黄峰博客管理系统</title>
<link rel="stylesheet" type="text/css" href="/web/backweb/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="/web/backweb/css/style.css">
<link rel="stylesheet" type="text/css" href="/web/backweb/css/login.css">
<link rel="apple-touch-icon-precomposed" href="/web/backweb/images/icon/icon.png">
<!--<link rel="shortcut icon" href="/web/backweb/images/icon/favicon.ico">-->
<script src="/web/backweb/js/jquery-2.1.4.min.js"></script>
<!--[if gte IE 9]>
  <script src="/web/backweb/js/jquery-1.11.1.min.js" type="text/javascript"></script>
  <script src="/web/backweb/js/html5shiv.min.js" type="text/javascript"></script>
  <script src="/web/backweb/js/respond.min.js" type="text/javascript"></script>
  <script src="/web/backweb/js/selectivizr-min.js" type="text/javascript"></script>
<![endif]-->
<!--[if lt IE 9]>
  <script>window.location.href='upgrade-browser.html';</script>
<![endif]-->
</head>

<body class="user-select">
<div class="container">
  <div class="siteIcon"><img src="/web/backweb/images/icon/icon.png" alt="" data-toggle="tooltip" data-placement="top" title="欢迎使用异清轩博客管理系统" draggable="false" /></div>
  <form action="" method="post" autocomplete="off" class="form-signin">
    {% csrf_token %}
    <h2 class="form-signin-heading">管理员注册</h2>
    <label for="userName" class="sr-only">用户名</label>
    <input type="text" id="userName" name="username" class="form-control" placeholder="请输入用户名" required autofocus autocomplete="off" maxlength="10">
    <span>{{ errors.username }}</span>
    <label for="userPwd" class="sr-only">密码</label>
    <input type="password" id="userPwd" name="userpwd" class="form-control" placeholder="请输入密码" required autocomplete="off" maxlength="18">
    <span>{{ errors.userpwd }}</span>
    <label for="userPwd" class="sr-only">确认密码</label>
    <input type="password" id="againPwd" name="againpwd" class="form-control" placeholder="请输入密码" required autocomplete="off" maxlength="18">
    <span>{{ errors.againpwd }}</span>
    <a href=""><button class="btn btn-lg btn-primary btn-block" type="submit" id="signinSubmit">登录</button></a>
  </form>
  <div class="footer">
    <p><a href="" data-toggle="tooltip" data-placement="left" title="不知道自己在哪?">回到后台 →</a></p>
  </div>
</div>
<script src="/web/backweb/js/bootstrap.min.js"></script>
<script>
$('[data-toggle="tooltip"]').tooltip();
window.oncontextmenu = function(){
	//return false;
};
$('.siteIcon img').click(function(){
	window.location.reload();
});
$('#signinSubmit').click(function(){
	if($('#userName').val() === ''){
		$(this).text('用户名不能为空');
	}else if($('#userPwd').val() === ''){
		$(this).text('密码不能为空');
	}else{
		$(this).text('请稍后...');
	}
});
</script>
</body>
</html>